name: tasky
description: Personal To-Do assistant.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  easy_localization: ^3.0.1
  auto_route: ^4.0.1
  drift: ^1.3.0
  timezone: ^0.8.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.8
  path: ^1.8.0
  intl: ^0.17.0
  flutter_slidable: ^1.2.0
  flutter_local_notifications: ^9.2.0
  flutter_native_timezone: ^2.0.0
  uni_links: ^0.5.1
  permission_handler: ^9.2.0
  flutter_launcher_icons: ^0.9.2
  flutter_dotenv: ^5.0.2
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  auto_route_generator: ^4.0.0
  drift_dev: ^1.3.0
  build_runner: ^2.1.7
  flutter_native_splash: ^2.1.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  image: assets/icons/app_icon.png
  color: "#42a5f5"

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/
    - assets/translations/
    - assets/icons/
