name: tasky
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  moor_flutter: ^4.0.0
  flutter_bloc: ^7.3.1
  get_it: ^7.2.0
  easy_localization: ^3.0.0
  auto_route: ^3.0.3
  moor: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.0.1
  moor_generator: ^4.6.0
  build_runner: ^2.1.4

flutter:
  uses-material-design: true