name: tasky
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.1
  get_it: ^7.2.0
  easy_localization: ^3.0.0
  auto_route: ^3.0.3
  drift: ^1.0.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  intl: ^0.17.0
  flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.0.1
  drift_dev: ^1.0.2
  build_runner: ^2.1.4

flutter:
  uses-material-design: true